# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.txtIP = QtWidgets.QLineEdit(self.centralwidget)
        self.txtIP.setObjectName("txtIP")
        self.hboxlayout.addWidget(self.txtIP)
        self.txtPort = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPort.setObjectName("txtPort")
        self.hboxlayout.addWidget(self.txtPort)
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setObjectName("btnConnect")
        self.hboxlayout.addWidget(self.btnConnect)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.txtChat = QtWidgets.QTextEdit(self.centralwidget)
        self.txtChat.setReadOnly(True)
        self.txtChat.setObjectName("txtChat")
        self.vboxlayout.addWidget(self.txtChat)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.txtMessage = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMessage.setObjectName("txtMessage")
        self.hboxlayout1.addWidget(self.txtMessage)
        self.btnSend = QtWidgets.QPushButton(self.centralwidget)
        self.btnSend.setObjectName("btnSend")
        self.hboxlayout1.addWidget(self.btnSend)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.txtPlain = QtWidgets.QTextEdit(self.centralwidget)
        self.txtPlain.setObjectName("txtPlain")
        self.vboxlayout.addWidget(self.txtPlain)
        self.txtCipher = QtWidgets.QTextEdit(self.centralwidget)
        self.txtCipher.setObjectName("txtCipher")
        self.vboxlayout.addWidget(self.txtCipher)
        self.txtKey = QtWidgets.QTextEdit(self.centralwidget)
        self.txtKey.setObjectName("txtKey")
        self.vboxlayout.addWidget(self.txtKey)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AES-RSA Client"))
        self.txtIP.setPlaceholderText(_translate("MainWindow", "IP"))
        self.txtPort.setPlaceholderText(_translate("MainWindow", "Port"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.btnSend.setText(_translate("MainWindow", "Send"))
        self.label.setText(_translate("MainWindow", "--- AES / RSA ---"))
        self.txtPlain.setPlaceholderText(_translate("MainWindow", "Plaintext"))
        self.txtCipher.setPlaceholderText(_translate("MainWindow", "Ciphertext (AES)"))
        self.txtKey.setPlaceholderText(_translate("MainWindow", "Encrypted AES Key (RSA)"))
