# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 360)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 0, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 160, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 50, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(430, 160, 47, 13))
        self.label_5.setObjectName("label_5")
        self.btngenkey = QtWidgets.QPushButton(self.centralwidget)
        self.btngenkey.setGeometry(QtCore.QRect(440, 0, 81, 23))
        self.btngenkey.setObjectName("btngenkey")
        self.btnencrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnencrypt.setGeometry(QtCore.QRect(70, 220, 75, 23))
        self.btnencrypt.setObjectName("btnencrypt")
        self.btndecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btndecrypt.setGeometry(QtCore.QRect(270, 220, 75, 23))
        self.btndecrypt.setObjectName("btndecrypt")
        self.btnsign = QtWidgets.QPushButton(self.centralwidget)
        self.btnsign.setGeometry(QtCore.QRect(480, 220, 75, 23))
        self.btnsign.setObjectName("btnsign")
        self.btnverify = QtWidgets.QPushButton(self.centralwidget)
        self.btnverify.setGeometry(QtCore.QRect(660, 220, 75, 23))
        self.btnverify.setObjectName("btnverify")
        self.txtplaintext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtplaintext.setGeometry(QtCore.QRect(70, 40, 271, 61))
        self.txtplaintext.setObjectName("txtplaintext")
        self.txtciphertext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtciphertext.setGeometry(QtCore.QRect(70, 140, 271, 61))
        self.txtciphertext.setObjectName("txtciphertext")
        self.txtinfo = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtinfo.setGeometry(QtCore.QRect(500, 40, 231, 61))
        self.txtinfo.setObjectName("txtinfo")
        self.txtsign = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtsign.setGeometry(QtCore.QRect(500, 140, 231, 61))
        self.txtsign.setObjectName("txtsign")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plantext:"))
        self.label_3.setText(_translate("MainWindow", "Ciphertext:"))
        self.label_4.setText(_translate("MainWindow", "Infomation:"))
        self.label_5.setText(_translate("MainWindow", "Signiture:"))
        self.btngenkey.setText(_translate("MainWindow", "Generate Keys"))
        self.btnencrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btndecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btnsign.setText(_translate("MainWindow", "Sign"))
        self.btnverify.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
